#!/usr/bin/python

rules = {	
	'extensions'		:	['.php', '.js', '.module', '.inc'],
	'topdir'			:	'.',
	'scan_level'		:	['high'],
	'ignore'			:   [],
	'scan_folders'		:	['application','assets'],
	'print_ok'			:	False,
	
	
	'rule_set'	: 
	{
		'.php': 
		{
		'specific'	:	{

			'database.php' : {
						'PASSWORD_TOKEN' : {
								"db\\['production'\\]\\['password'\\]\\s+=\\s+('|\')" : 'TOKEN'
						}
			}, 

			'config.php' : {
						'BASE_URL' : {"base_url.*?'\S+';$" : 'NON-BLANK'},
						'QUERY_STRINGS' : {"enable_query_strings.*?TRUE;$" : 'FALSE'},
						'ENCRYPTION_KEY' : {"encryption_key.*?('|\')" : 'TOKEN'},
						'ENCRYPT_COOKIE' :  {"sess_encrypt_cookie.*?FALSE;$" : 'TRUE'},
						'SESSION_DB' :  {"sess_use_database.*?FALSE;$" : 'TRUE'},
						'COOKIE_SECURE' : {'cookie_secure.*?FALSE;$' : 'TRUE'},
						'GLOBAL_XSS' : {'global_xss_filtering.*?FALSE;$' : 'TRUE'},
						'CSRF' : {'csrf_protection.*?FALSE;$' : 'TRUE'},
						'SHORT_TAGS' : {"rewrite_short_tags.*?TRUE;$" : 'FALSE'}
			}	
		},

		'general' : {

			'high' : [
						'preg_replace\\(.*/e',
						'\$_GET',
						'\$_POST',
						'\$_COOKIE',
						'\$_REQUIRE',
						'phpinfo\\(',
						'ini_set\\(',
						
			],

			'medium' : [
						'chgrp\\(',
						'chmod\\(',
						'chown\\(',
						'copy\\(',
						'file_get_contents\\(',
						'file_put_contents\\(',
						'lchgrp\\(',
						'lchown\\(',
						'link\\(',
						'mkdir\\(',
						'move_uploaded_file\\(',
						'rename\\(',
						'rmdir\\(',
						'symlink\\(',
						'tempnam\\(',
						'touch\\(',
						'unlink\\('
			],

			'low' : [
						'include\\(',
						"include ('|\')",
						'include_once\\(',
						"include_once ('|\')",
						'require\\(',
						"require ('|\')",
						'require_once\\(',
						"require_once ('|\')",
						'imagepng\\(',
						'imagewbmp\\(',
						'image2wbmp\\(', 
						'imagejpeg\\(',
						'imagexbm\\(',
						'imagegif\\(',
						'imagegd\\(',
						'imagegd2\\(',
						'iptcembed\\(',
						'ftp_get\\(',
						'ftp_nb_get\\(',
						'file_exists\\(',
						'file\\(',
						'fileatime\\(',
						'filectime\\(',
						'filegroup\\(',
						'fileinode\\(',
						'filemtime\\(',
						'fileowner\\(',
						'fileperms\\(',
						'filesize\\(',
						'filetype\\(',
						'glob\\(',
						'is_dir\\(',
						'is_executable\\(',
						'is_file\\(',
						'is_link\\(',
						'is_readable\\(',
						'is_uploaded_file\\(',
						'is_writable\\(',
						'is_writeable\\(',
						'linkinfo\\(',
						'lstat\\(',
						'parse_ini_file\\(',
						'pathinfo\\(',
						'readfile\\(',
						'readlink\\(',
						'realpath\\(',
						'stat\\(',
						'gzfile\\(',
						'readgzfile\\(',
						'getimagesize\\(',
						'imagecreatefromgif\\(',
						'imagecreatefromjpeg\\(',
						'imagecreatefrompng\\(',
						'imagecreatefromwbmp\\(',
						'imagecreatefromxbm\\(',
						'imagecreatefromxpm\\(',
						'ftp_put\\(',
						'ftp_nb_put\\(',
						'exif_read_data\\(',
						'read_exif_data\\(',
						'exif_thumbnail\\(',
						'exif_imagetype\\(',
						'hash_file\\(',
						'hash_hmac_file\\(',
						'hash_update_file\\(',
						'md5_file\\(',
						'sha1_file\\(',
						'highlight_file\\(',
						'show_source\\(',
						'php_strip_whitespace\\(',
						'get_meta_tags\\(',
						'ob_start\\(', 
						'array_diff_uassoc\\(',
						'array_diff_ukey\\(',
						'array_filter\\(',
						'array_intersect_uassoc\\(',
						'array_intersect_ukey\\(',
						'array_map\\(',
						'array_reduce\\(',
						'array_udiff_assoc\\(',
						'array_udiff_uassoc\\(',
						'array_udiff\\(',
						'array_uintersect_assoc\\(',
						'array_uintersect_uassoc\\(',
						'array_uintersect\\(',
						'array_walk_recursive\\(',
						'array_walk\\(',
						'assert_options\\(',
						'uasort\\(',
						'uksort\\(',
						'usort\\(',
						'preg_replace_callback\\(',
						'spl_autoload_register\\(',
						'iterator_apply\\(',
						'call_user_func\\(',
						'call_user_func_array\\(',
						'register_shutdown_function\\(',
						'register_tick_function\\(',
						'set_error_handler\\(',
						'set_exception_handler\\(',
						'session_set_save_handler\\(',
						'sqlite_create_aggregate\\(',
						'sqlite_create_function\\('
			]
		}
		
		},


		'.module': 
		{
		'specific'	:	{

			
		},

		'general' : {

			'high' : [
						'print_r',
						'var_dump',
						'exec\\(', 
						'passthru\\(',
						'system\\(',
						'shell_exec\\(',
						'`', 
						'popen\\(', 
						'proc_open\\(',
						'pcntl_exec\\(', 
						'eval\\(',
						'assert\\(',
						'create_function\\(',
						'preg_replace\\(.*/e',
						'\$_GET',
						'\$_POST',
						'\$_COOKIE',
						'\$_REQUIRE',
						'phpinfo\\(',
						'posix_mkfifo\\(',
						'posix_getlogin\\(',
						'posix_ttyname\\(',
						'getenv\\(',
						'get_current_user\\(',
						'proc_get_status\\(',
						'get_cfg_var\\(',
						'disk_free_space\\(',
						'disk_total_space\\(',
						'diskfreespace\\(',
						'getcwd\\(',
						'getlastmo\\(',
						'getmygid\\(',
						'getmyinode\\(',
						'getmypid\\(',
						'getmyuid\\(',
						'extract\\(',
						'parse_str\\(',
						'putenv\\(',
						'ini_set\\(',
						'proc_nice\\(',
						'proc_terminate\\(',
						'proc_close\\(',
						'pfsockopen\\(',
						'fsockopen\\(',
						'apache_child_terminate\\(',
						'posix_kill\\(',
						'posix_mkfifo\\(',
						'posix_setpgid\\(',
						'posix_setsid\\(',
						'posix_setuid\\('
			],

			'medium' : [
						'chgrp\\(',
						'chmod\\(',
						'chown\\(',
						'copy\\(',
						'file_get_contents\\(',
						'file_put_contents\\(',
						'lchgrp\\(',
						'lchown\\(',
						'link\\(',
						'mkdir\\(',
						'move_uploaded_file\\(',
						'rename\\(',
						'rmdir\\(',
						'symlink\\(',
						'tempnam\\(',
						'touch\\(',
						'unlink\\('

			],

			'low' : [
						'include\\(',
						"include ('|\')",
						'include_once\\(',
						"include_once ('|\')",
						'require\\(',
						"require ('|\')",
						'require_once\\(',
						"require_once ('|\')",
						'imagepng\\(',
						'imagewbmp\\(',
						'image2wbmp\\(', 
						'imagejpeg\\(',
						'imagexbm\\(',
						'imagegif\\(',
						'imagegd\\(',
						'imagegd2\\(',
						'iptcembed\\(',
						'ftp_get\\(',
						'ftp_nb_get\\(',
						'file_exists\\(',
						'file\\(',
						'fileatime\\(',
						'filectime\\(',
						'filegroup\\(',
						'fileinode\\(',
						'filemtime\\(',
						'fileowner\\(',
						'fileperms\\(',
						'filesize\\(',
						'filetype\\(',
						'glob\\(',
						'is_dir\\(',
						'is_executable\\(',
						'is_file\\(',
						'is_link\\(',
						'is_readable\\(',
						'is_uploaded_file\\(',
						'is_writable\\(',
						'is_writeable\\(',
						'linkinfo\\(',
						'lstat\\(',
						'parse_ini_file\\(',
						'pathinfo\\(',
						'readfile\\(',
						'readlink\\(',
						'realpath\\(',
						'stat\\(',
						'gzfile\\(',
						'readgzfile\\(',
						'getimagesize\\(',
						'imagecreatefromgif\\(',
						'imagecreatefromjpeg\\(',
						'imagecreatefrompng\\(',
						'imagecreatefromwbmp\\(',
						'imagecreatefromxbm\\(',
						'imagecreatefromxpm\\(',
						'ftp_put\\(',
						'ftp_nb_put\\(',
						'exif_read_data\\(',
						'read_exif_data\\(',
						'exif_thumbnail\\(',
						'exif_imagetype\\(',
						'hash_file\\(',
						'hash_hmac_file\\(',
						'hash_update_file\\(',
						'md5_file\\(',
						'sha1_file\\(',
						'highlight_file\\(',
						'show_source\\(',
						'php_strip_whitespace\\(',
						'get_meta_tags\\(',
						'ob_start\\(', 
						'array_diff_uassoc\\(',
						'array_diff_ukey\\(',
						'array_filter\\(',
						'array_intersect_uassoc\\(',
						'array_intersect_ukey\\(',
						'array_map\\(',
						'array_reduce\\(',
						'array_udiff_assoc\\(',
						'array_udiff_uassoc\\(',
						'array_udiff\\(',
						'array_uintersect_assoc\\(',
						'array_uintersect_uassoc\\(',
						'array_uintersect\\(',
						'array_walk_recursive\\(',
						'array_walk\\(',
						'assert_options\\(',
						'uasort\\(',
						'uksort\\(',
						'usort\\(',
						'preg_replace_callback\\(',
						'spl_autoload_register\\(',
						'iterator_apply\\(',
						'call_user_func\\(',
						'call_user_func_array\\(',
						'register_shutdown_function\\(',
						'register_tick_function\\(',
						'set_error_handler\\(',
						'set_exception_handler\\(',
						'session_set_save_handler\\(',
						'sqlite_create_aggregate\\(',
						'sqlite_create_function\\('
			]
		}
		
		},

		'.inc': 
		{
		'specific'	:	{

			
		},

		'general' : {

			'high' : [
						'print_r',
						'var_dump',
						'exec\\(', 
						'passthru\\(',
						'system\\(',
						'shell_exec\\(',
						'`', 
						'popen\\(', 
						'proc_open\\(',
						'pcntl_exec\\(', 
						'eval\\(',
						'assert\\(',
						'create_function\\(',
						'preg_replace\\(.*/e',
						'\$_GET',
						'\$_POST',
						'\$_COOKIE',
						'\$_REQUIRE',
						'phpinfo\\(',
						'posix_mkfifo\\(',
						'posix_getlogin\\(',
						'posix_ttyname\\(',
						'getenv\\(',
						'get_current_user\\(',
						'proc_get_status\\(',
						'get_cfg_var\\(',
						'disk_free_space\\(',
						'disk_total_space\\(',
						'diskfreespace\\(',
						'getcwd\\(',
						'getlastmo\\(',
						'getmygid\\(',
						'getmyinode\\(',
						'getmypid\\(',
						'getmyuid\\(',
						'extract\\(',
						'parse_str\\(',
						'putenv\\(',
						'ini_set\\(',
						'proc_nice\\(',
						'proc_terminate\\(',
						'proc_close\\(',
						'pfsockopen\\(',
						'fsockopen\\(',
						'apache_child_terminate\\(',
						'posix_kill\\(',
						'posix_mkfifo\\(',
						'posix_setpgid\\(',
						'posix_setsid\\(',
						'posix_setuid\\('
			],

			'medium' : [
						'chgrp\\(',
						'chmod\\(',
						'chown\\(',
						'copy\\(',
						'file_get_contents\\(',
						'file_put_contents\\(',
						'lchgrp\\(',
						'lchown\\(',
						'link\\(',
						'mkdir\\(',
						'move_uploaded_file\\(',
						'rename\\(',
						'rmdir\\(',
						'symlink\\(',
						'tempnam\\(',
						'touch\\(',
						'unlink\\('

			],

			'low' : [
						'include\\(',
						"include ('|\')",
						'include_once\\(',
						"include_once ('|\')",
						'require\\(',
						"require ('|\')",
						'require_once\\(',
						"require_once ('|\')",
						'imagepng\\(',
						'imagewbmp\\(',
						'image2wbmp\\(', 
						'imagejpeg\\(',
						'imagexbm\\(',
						'imagegif\\(',
						'imagegd\\(',
						'imagegd2\\(',
						'iptcembed\\(',
						'ftp_get\\(',
						'ftp_nb_get\\(',
						'file_exists\\(',
						'file\\(',
						'fileatime\\(',
						'filectime\\(',
						'filegroup\\(',
						'fileinode\\(',
						'filemtime\\(',
						'fileowner\\(',
						'fileperms\\(',
						'filesize\\(',
						'filetype\\(',
						'glob\\(',
						'is_dir\\(',
						'is_executable\\(',
						'is_file\\(',
						'is_link\\(',
						'is_readable\\(',
						'is_uploaded_file\\(',
						'is_writable\\(',
						'is_writeable\\(',
						'linkinfo\\(',
						'lstat\\(',
						'parse_ini_file\\(',
						'pathinfo\\(',
						'readfile\\(',
						'readlink\\(',
						'realpath\\(',
						'stat\\(',
						'gzfile\\(',
						'readgzfile\\(',
						'getimagesize\\(',
						'imagecreatefromgif\\(',
						'imagecreatefromjpeg\\(',
						'imagecreatefrompng\\(',
						'imagecreatefromwbmp\\(',
						'imagecreatefromxbm\\(',
						'imagecreatefromxpm\\(',
						'ftp_put\\(',
						'ftp_nb_put\\(',
						'exif_read_data\\(',
						'read_exif_data\\(',
						'exif_thumbnail\\(',
						'exif_imagetype\\(',
						'hash_file\\(',
						'hash_hmac_file\\(',
						'hash_update_file\\(',
						'md5_file\\(',
						'sha1_file\\(',
						'highlight_file\\(',
						'show_source\\(',
						'php_strip_whitespace\\(',
						'get_meta_tags\\(',
						'ob_start\\(', 
						'array_diff_uassoc\\(',
						'array_diff_ukey\\(',
						'array_filter\\(',
						'array_intersect_uassoc\\(',
						'array_intersect_ukey\\(',
						'array_map\\(',
						'array_reduce\\(',
						'array_udiff_assoc\\(',
						'array_udiff_uassoc\\(',
						'array_udiff\\(',
						'array_uintersect_assoc\\(',
						'array_uintersect_uassoc\\(',
						'array_uintersect\\(',
						'array_walk_recursive\\(',
						'array_walk\\(',
						'assert_options\\(',
						'uasort\\(',
						'uksort\\(',
						'usort\\(',
						'preg_replace_callback\\(',
						'spl_autoload_register\\(',
						'iterator_apply\\(',
						'call_user_func\\(',
						'call_user_func_array\\(',
						'register_shutdown_function\\(',
						'register_tick_function\\(',
						'set_error_handler\\(',
						'set_exception_handler\\(',
						'session_set_save_handler\\(',
						'sqlite_create_aggregate\\(',
						'sqlite_create_function\\('
			]
		}
		
		},



		
		'.js': 
		{
		'specific'			:	{},

		'general' : {

			'high' : [
						'eval',
						'console\.log',
						'cookie',
						'window\.location\.href'
			],

			'medium' : [
						'history\.current',
						'history\.next',
					

			],

			'low' : []
		}
		
		
		}
	}
	
}