$schema: "http://json-schema.org/draft-07/schema#"
title: "eye-of-sauron rule pack"
type: object
required:
  - extensions
  - rule_set
properties:
  extensions:
    type: array
    items:
      type: string
  rule_set:
    type: object
    additionalProperties:
      type: object
      properties:
        specific:
          type: object
        general:
          type: object
          properties:
            high:
              type: array
            medium:
              type: array
            low:
              type: array
