"""Render writing prompts as a beautiful HTML email."""
from datetime import date


_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  background: #0f0f0f;
  font-family: Georgia, 'Times New Roman', serif;
  color: #e8e8e8;
  padding: 0;
}
.wrapper {
  max-width: 600px;
  margin: 0 auto;
  padding: 32px 24px;
}
.header {
  text-align: center;
  margin-bottom: 36px;
  padding-bottom: 24px;
  border-bottom: 1px solid #2a2a2a;
}
.header h1 {
  font-size: 1.1rem;
  font-weight: 400;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: #888;
  margin-bottom: 6px;
}
.header .date {
  font-size: 0.85rem;
  color: #555;
  font-family: system-ui, sans-serif;
}
.card {
  margin-bottom: 24px;
  border-radius: 6px;
  overflow: hidden;
  border: 1px solid #222;
}
.card-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 16px;
  font-family: system-ui, sans-serif;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: #ccc;
}
.card-body {
  background: #161616;
  padding: 20px 20px 22px;
  font-size: 1.05rem;
  line-height: 1.75;
  color: #ddd;
}
details.beats {
  background: #111;
  border-top: 1px solid #222;
}
details.beats summary {
  padding: 10px 20px;
  font-family: system-ui, sans-serif;
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: #555;
  cursor: pointer;
  user-select: none;
  list-style: none;
}
details.beats summary::-webkit-details-marker { display: none; }
details.beats summary::after {
  content: " ▾";
  font-size: 0.65rem;
}
details.beats[open] summary::after {
  content: " ▴";
}
details.beats summary:hover { color: #888; }
details.beats ol {
  padding: 4px 20px 18px 36px;
  font-family: system-ui, sans-serif;
  font-size: 0.82rem;
  line-height: 1.7;
  color: #666;
}
details.beats ol li { margin-bottom: 4px; }
details.beats ol li:last-child { margin-bottom: 0; }
.footer {
  margin-top: 36px;
  padding-top: 20px;
  border-top: 1px solid #1e1e1e;
  font-family: system-ui, sans-serif;
  font-size: 0.72rem;
  color: #444;
  text-align: center;
  line-height: 1.6;
}
"""


def render_email(
    prompts: dict[str, str],
    genres: dict,
    voice_names: dict | None = None,
    beats_map: dict | None = None,
) -> str:
    today = date.today().strftime("%A, %B %-d, %Y")

    cards = []
    for key, text in prompts.items():
        g = genres.get(key, {})
        icon = g.get("icon", "✦")
        label = g.get("label", key.title())
        color = g.get("color", "#1a1a1a")

        vname = (voice_names or {}).get(key)
        voice_badge = (
            f'<span style="margin-left: auto; font-weight: 400; opacity: 0.6; '
            f'text-transform: none; letter-spacing: 0;">{vname}</span>'
            if vname else ""
        )

        beats = (beats_map or {}).get(key, [])
        if beats:
            beat_items = "\n".join(f"    <li>{b}</li>" for b in beats)
            beats_html = f"""
  <details class="beats">
    <summary>Plot beats</summary>
    <ol>
{beat_items}
    </ol>
  </details>"""
        else:
            beats_html = ""

        cards.append(f"""
  <div class="card">
    <div class="card-header" style="background: {color};">
      <span>{icon}</span>
      <span>{label}</span>
      {voice_badge}
    </div>
    <div class="card-body">{text}</div>{beats_html}
  </div>""")

    cards_html = "\n".join(cards)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Daily Writing Spark — {today}</title>
  <style>{_CSS}</style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>✦ Daily Writing Spark</h1>
      <div class="date">{today}</div>
    </div>
    {cards_html}
    <div class="footer">
      Generated by creative-tools &middot; GitHub Models &middot; {today}
    </div>
  </div>
</body>
</html>"""
